#!/bin/sh
python createdb.py default
python trainings/manage.py syncdb --noinput
python trainings/manage.py migrate
python mkadmin.py
mkdir -p /home/dotcloud/data/media /home/dotcloud/data/static
python trainings/manage.py collectstatic --noinput